### ISSUE TITLE
WolfSheep Mesa/Agents Scheduler

### ISSUE THREAD

**Issue by Libbum** [JuliaDynamics/ABM_Framework_Comparisons#2]
At the moment, we use a non-standard scheduler for Wolf Sheep (compared to the Mesa standard library). Need to verify if this is appropriate / fair etc.

**Comment by Libbum** [comment]
See JuliaDynamics/Agents.jl#394 for reference.

**Comment by rht** [comment]
I have a slightly related noob question, that I figure I'd ask here instead of opening up a new issue. The Agents.jl equivalent of the not-yet-in-lib `RandomActivationByBreed` class is `by_type`. The function name by itself doesn't give away that it is indeed a scheduler. Then I tried to look at the namespace it comes from. But Agents.jl seems to be heavily using `using` (no pun intended) instead of `import`. From reading https://julialang.zulipchat.com/#narrow/stream/225540-gripes/topic/Name.20spacing, it was stated that `using Foo` instead of `using Foo: bar, baz` is used mainly in REPL for quick prototyping (this message in particular: https://julialang.zulipchat.com/#narrow/stream/225540-gripes/topic/Name.20spacing/near/232932834).

Though at the end of the day, I know that it is a scheduler by how it is used: https://github.com/JuliaDynamics/Agents.jl/blob/b295fcf90da1635fe8fe04af16d651732f2eba00/src/models/predator_prey.jl#L63. Is it common practice in Julia code to name a function as concise as possible, just enough to differentiate itself from other functions (`fastest`, `by_id`, `random_activation`, `partial_activation`, `property_activation`) but no need to make it standalone? If so, why do some scheduler functions have `_activation` in their names?

**Comment by rht** [comment]
Related: https://github.com/projectmesa/mesa/issues/900

**Comment by Datseris** [comment]
Heh, we want to change the name of schedulers to be coherent, see : https://github.com/JuliaDynamics/Agents.jl/issues/363 .

However I do not fully agree with what you read on name spacing, of not using `using X` in favor of `using X: a, b`, because Julia has the wonderful macro `@which name_of_thing` which tells you what is the `Module` that generates the name. Some times in package development you need a lot of names from a Module, or you might not know in advance which names you will need.

Overall however I do agree that doing `using Module: a, b` would be preferred in many scenarios.

**Comment by rht** [comment]
> Because of bad design that we will change in the near future. :)

Got it. Looking forward to it.

> Some times in package development you need a lot of names from a Module, or you might not know in advance which names you will need.

In that case, there is `import Module` for `Module.a`.

> because Julia has the wonderful macro @which name_of_thing which tells you what is the Module that generates the name. 

Only true in a REPL, not while reading a code from an editor. Unless people usually read a .jl file inside a Pluto IDE.

**Comment by Libbum** [comment]
Agents.jl Wolf-Sheep has been updated. We're still in line with Netlogo, staging Sheep, then Wolves, then grass; although we're using our `by_property` rather than `by_type`.

**Comment by Libbum** [comment]
When the scheduler in mesa#900 is merged, the LOC level can be dropped in the comparison table. This change wont affect the benchmark results heavily. We could go down the path of modifying the Netlogo version to have a complete random activation of all three agent types, but that seems to be removing capacity rather than testing the breadth of framework options. So I'm voting to keep the scheduler system as-is & will update the LOC value once the explicit scheduler is no-longer required.

**Comment by rht** [comment]
I looked at `by_property`'s implementation. Have several questions:
- https://github.com/JuliaDynamics/Agents.jl/blob/0870c7e3e35c8add2b2ad00cb90261a19228dbaa/src/submodules/schedulers.jl#L83 I assume that this `ids` is always different for any simulation because Julia's `keys()` accessor is nondeterministic, as stated by the docstring of `fastest`. Shouldn't a simulation be reproducible when a random seed is given?
- How is `by_property` behaviorally different from `by_type` in the WolfSheep example? The `:type` property than the agent type seems to be a 1-to-1 mapping to me.

**Comment by Libbum** [comment]
You're right on both accounts in this instance. We've changed the way WolfSheep is implemented, but still want to have activation order separated. As far as the example is concerned, there is a 1-to-1 mapping. The difference is functional for Agents.jl though, since we have the option of either ordering by the struct of an agent or a property within the struct.

Indeed, keys is nondeterministic, although that's against the internal rng algorithm that's not guaranteed to remain the same across julia versions. Providing a seed to a `MersenneTwister` would yield a different result in julia 1.5.2 and 1.6 for example. The solution to that is to use `StableRNG` as your pseudo-rng pool if that is something a model requires. Run to run though, this is not an issue. We could even add a `shuffle!` into the `by_property` scheduler and have `by_property_randomly` and this would be reproducible with the same seed.

**Comment by rht** [comment]
Also, I'm not sure how material the performance loss is, `by_type` seems to construct this `sets` (https://github.com/JuliaDynamics/Agents.jl/blob/0870c7e3e35c8add2b2ad00cb90261a19228dbaa/src/submodules/schedulers.jl#L102-L106) object from scratch every time it is called. Wouldn't it be more efficient to somehow cache it and reuse it for every time a model step is taken? Mesa's not-yet-default `RandomActivationByBreed`, during its initialization, constructs a `Dict[object, Dict[int, Agent]]` where the `object` is agent class, int is agent's unique id.

**Comment by Libbum** [comment]
That's definitely an issue, but it's one we're going to shy away from for the moment. There will be a revamp of how we deal with multi-agent types in the near future. We've hit a wall with the current methodology and it needs a rethink. See [this comment thread](https://github.com/JuliaDynamics/Agents.jl/issues/445#issuecomment-811043314).

**Comment by rht** [comment]
You are using `StableRNGs` in space_test.jl and scheduler_tests.jl, but haven't used it in the examples. Since the examples are also meant to showcase best practices, should I raise an issue in https://github.com/JuliaDynamics/Agents.jl and here to say that the examples should be deterministic and so on? Or is it better instead to just document to recommend using `StableRNGs` somewhere in the docs?

As with `collect(keys(...))`. I tried:
```
julia> rng = StableRNG(50)
julia> Random.seed!(rng, 100)
julia> a = Dict(1 => 1, 2 => 2, 3=>3, 5=>5, 4=>4)
Dict{Int64,Int64} with 5 entries:
  4 => 4
  2 => 2
  3 => 3
  5 => 5
  1 => 1
```

I reinitialized the dictionary `a` several times with different `StableRNG` seeds, and the order is always 4, 2, 3, 5, 1. And doing `collect(keys(a))` several times does not change the order in this result. Even after a restart of my REPL, the order is still the same. Does this mean the order of agent ids of `by_property` is always the same for all the `step`s? I'm on Julia 1.5.3.

**Comment by Libbum** [comment]
This is expected behaviour. You'll get the same with MersenneTwister in this case too. There's just a *possibility* that these keys will be different in 1.6. The values in the tests that are using StableRNGs are a consequence of this, but for the most part this is really not an issue.

> Does this mean the order of agent ids of `by_property` is always the same for all the steps?

Yes. As you said above, it's essentially separating the agents the same as `fastest` does (which is the same behaviour as Netlogo). We could randomise this order as well, but that's not the case currently.

**Comment by rht** [comment]
Do you think it is better to update the Netlogo code at both this repo and https://github.com/NetLogo/models/blob/master/Sample%20Models/Biology/Wolf%20Sheep%20Predation.nlogo to do shuffling?
We don't want a bias in the execution order of the agents.

I think this is how to do the shuffling? http://ccl.northwestern.edu/netlogo/docs/dictionary.html#up-to-n-of.

**Comment by Libbum** [comment]
I have no arguments against doing that. Will open an issue.
