### ISSUE TITLE
Wolf Sheep Grass in Mason?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ABM_Framework_Comparisons#31]
Seems like there is some code for WSG in MASON: https://github.com/isislab-unisa/ABM_Comparison/tree/main/MASON/wsg  why haven't we included this here @Tortar ?

**Comment by Tortar** [comment]
For the same reason why we don't include ForestFire: https://github.com/isislab-unisa/ABM_Comparison/blob/main/MASON/forestfire/ForestFire.java

This is part of the step:

```java
            int minmax = (step + 1 < gridHeight - 1) ? (int) step + 1 : gridHeight - 1;
            for (int j = minmax; j >= 0; j--) {
                for (int i = 0; i < gridHeight; i++) {
                    // System.out.println("i: " + i + " j: " + j);
                    int v = myfield.get(i,j);
                    if (v == GREEN) {
                        for (int k = i-1; k <= i+1; k++) {
                            for (int l = j-1; l <= j+1; l++) {
                                if (k >= 0 && k < gridWidth && l >= 0 && l < gridHeight
                                    && (k != i || l != j)) {
                                    if (myfield.get(k,l) == BURNING) {
                                        myfield.set(i,j, BURNING);
                                        break;
                                    }
```

As you see they don't scan all the grid at each step because of `int minmax = (step + 1 < gridHeight - 1) ? (int) step + 1 : gridHeight - 1;`, so it's not fair to include it here.

I have more problems reading the code about `wsg` and so I can't judge if it can be included, let me know if you think it can

**Comment by Datseris** [comment]
for forest fire i don't understand what you mean.

also, can't we alter the code so that all of the grid is scanned...?

**Comment by Tortar** [comment]
Yes, sure we can. But for wolf-sheep-grass I find it more difficult to say what are the differences, but in the end I think we can deal with that before merging, will do PRs for each model
